# latexmk: pdfLaTeX + bibtex, como o modelo do PCS (TCC_PCS_EPUSP_2023).
$pdf_mode = 1;
$pdflatex = 'pdflatex -interaction=nonstopmode -file-line-error -synctex=1 %O %S';
$bibtex_use = 2;
$out_dir = 'build';
@default_files = ('parcial.tex');
# Roda o bibtex daqui (onde está referencias.bib), e não de dentro de build/.
# Com o padrão (fudge ligado), o MiKTeX não acha o .bib.
$bibtex_fudge = 0;
