#!/usr/bin/env python3
"""Generate Track B's C2 fixtures from the suite plus the hand analysis.

    python3 scripts/build-fixtures.py [--check]

Writes one C2 record per entry in ``irqrace.llm.fixture_specs.SPECS`` into
``fixtures/c2/``, rewrites ``fixtures/labels.json``, and validates everything
against the contract. ``--check`` regenerates into memory and fails if the
files on disk differ, so a spec edit that was never rebuilt is caught.

The two seeded fixtures from Track A's contract examples are kept as manifest
entries pointing at those files; they are not regenerated here.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / "src"))

from irqrace import contracts  # noqa: E402
from irqrace.llm import fixture_specs  # noqa: E402
from irqrace.llm.annotations import locate_suite, parse_file  # noqa: E402
from irqrace.llm.fixture_builder import build  # noqa: E402

OUT = REPO / "fixtures" / "c2"
MANIFEST = REPO / "fixtures" / "labels.json"

#: Every fixture is generated. The two hand-written examples in
#: ``contracts/`` were used as seeds until 2026-09-26, when strengthening the
#: label-leak test showed that ``c2-trap.json``'s provenance calls itself "the
#: planted-trap shape" -- which hands a model the answer the moment the record
#: is rendered into a prompt. Those files are Track A's and were left alone;
#: the same two candidates are built from their annotations instead.
SEEDED: list[dict] = []


def generate(suite: Path) -> tuple[dict[str, dict], list[dict]]:
    records: dict[str, dict] = {}
    entries: list[dict] = list(SEEDED)

    for spec in fixture_specs.SPECS:
        source = next((suite / spec.case).glob("*.c"))
        annotation = next(
            a
            for a in parse_file(source)
            if a.kind == spec.kind and a.index == spec.index
        )
        record = build(spec, annotation, suite)
        contracts.validate("c2", record, what=f"{spec.case} {spec.kind} #{spec.index}")

        name = f"{spec.case}-{spec.kind}-{spec.index}.json"
        records[name] = record
        entries.append(
            {
                "path": f"c2/{name}",
                "label": spec.label,
                # Drop the comment marker and the "1." / "1:" numbering; keep
                # the rest exactly as the suite writes it.
                "annotation": re.sub(
                    r"^//\s*\d+\s*[.:]\s*", "", annotation.raw
                ),
                "notes": spec.exercises,
            }
        )
    return records, entries


def manifest_document(entries: list[dict]) -> dict:
    return {
        "comment": [
            "Track B's labelled evaluation set (Roadmap W1). Target: 10 bug points",
            "and 10 traps. The label lives here and never inside a C2 record -- a",
            "context record is what the analyzer knows, and the label is exactly what",
            "it does not know.",
            "",
            "GENERATED by scripts/build-fixtures.py from irqrace/llm/fixture_specs.py.",
            "Edit the specs, not this file; the first two entries are hand-written and",
            "point at Track A's contract examples.",
            "",
            "'annotation' is the verbatim racebench 2.1_remarks line the fixture was",
            "built from. Ground truth in this suite is contested, so every label has to",
            "be traceable to the suite rather than to whoever typed it.",
        ],
        "target_per_label": 10,
        "fixtures": entries,
    }


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="fail if the files are stale")
    args = ap.parse_args()

    suite = locate_suite()
    if suite is None:
        print(
            "racebench not found. Clone it to ../racebench or set "
            "IRQRACE_RACEBENCH.",
            file=sys.stderr,
        )
        return 2

    records, entries = generate(suite)
    manifest = manifest_document(entries)

    stale = []
    for name, record in records.items():
        text = json.dumps(record, indent=2, ensure_ascii=False) + "\n"
        path = OUT / name
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != text:
                stale.append(path.name)
        else:
            OUT.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding="utf-8")

    text = json.dumps(manifest, indent=2, ensure_ascii=False) + "\n"
    if args.check:
        if MANIFEST.read_text(encoding="utf-8") != text:
            stale.append(MANIFEST.name)
        if stale:
            print("stale, rerun scripts/build-fixtures.py: " + ", ".join(stale))
            return 1
        print(f"up to date — {len(records)} generated + {len(SEEDED)} seeded")
        return 0

    MANIFEST.write_text(text, encoding="utf-8")
    bugs = sum(1 for e in entries if e["label"] == "bug_point")
    print(
        f"wrote {len(records)} records to {OUT.relative_to(REPO)} "
        f"and {MANIFEST.name}\n"
        f"  {bugs} bug points, {len(entries) - bugs} traps, "
        f"{len(entries)} total"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
